//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DejtProjekt.Recourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Country {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Country() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DejtProjekt.Recourses.Country", typeof(Country).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom.
        /// </summary>
        public static string Boom {
            get {
                return ResourceManager.GetString("Boom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        public static string Du {
            get {
                return ResourceManager.GetString("Du", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hem.
        /// </summary>
        public static string Hem {
            get {
                return ResourceManager.GetString("Hem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag.
        /// </summary>
        public static string Jag {
            get {
                return ResourceManager.GetString("Jag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Kontakt {
            get {
                return ResourceManager.GetString("Kontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om.
        /// </summary>
        public static string Om {
            get {
                return ResourceManager.GetString("Om", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprak.
        /// </summary>
        public static string Sprak {
            get {
                return ResourceManager.GetString("Sprak", resourceCulture);
            }
        }

        public static string Registrera
        {
            get
            {
                return ResourceManager.GetString("Registrera", resourceCulture);
            }
        }

        public static string Logga_in
        {
            get
            {
                return ResourceManager.GetString("Logga in", resourceCulture);
            }
        }
    }
}
